# Generated by Django 4.1.5 on 2023-01-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('submitted_by', models.CharField(max_length=50)),
                ('submit_date', models.DateField()),
                ('file_size', models.FileField(upload_to='')),
                ('file_path', models.FilePathField()),
                ('file_type', models.FileField(upload_to='')),
                ('file_name', models.TextField()),
                ('comments', models.CharField(max_length=100)),
                ('viewed_by', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField()),
                ('creation_date', models.DateField()),
            ],
        ),
    ]
