# Generated by Django 4.1.5 on 2023-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmedia',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='reviewmedia',
            name='submit_date',
        ),
        migrations.AddField(
            model_name='reviewmedia',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='file_path',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='file_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
    ]
