# Generated by Django 4.1.5 on 2023-01-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Review_Management', '0002_remove_reviewmedia_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review_Management.project'),
        ),
    ]
