# Generated by Django 4.1.5 on 2023-01-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Review_Management', '0003_project_alter_reviewmedia_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review_Management.department'),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review_Management.submittedby'),
        ),
        migrations.AlterField(
            model_name='reviewmedia',
            name='viewed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review_Management.viewedby'),
        ),
    ]
